import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {StyledNavBar} from '../styles/StyledComps/StyledNavBar.js'

import {HamburgerIcon} from '@chakra-ui/icons'
import { useEffect, useState } from 'react'
import { Box, HStack, IconButton, Menu, MenuButton, MenuItem, MenuList } from '@chakra-ui/react'

interface NavigationElement {
  title: string;
  url: string;
}

const Home: NextPage = () => {
  const menuList : Array<NavigationElement> = [
    { title: "Inicio", url: "/"},
    { title: "Alta", url: "#/alta"},
    { title: "Apertura", url: "#/apertura"},
    { title: "Transacciones", url: "#/transacciones"},
  ];


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <StyledNavBar>
        <div className='responsive'>
          <Menu >
            <MenuButton
              as={IconButton}
              aria-label='Options'
              icon={<HamburgerIcon className="burger-icon"/>}
              variant='outline'
            />
            <MenuList>
              { menuList.map( (m,i) =>{
                  return (
                    <MenuItem key={i}>
                      <a href={m.url}>{m.title}</a>
                    </MenuItem>
                  )
                })
              }
            </MenuList>
          </Menu>
        </div>

        <HStack spacing='24px' className="expanded">
          { menuList.map( (m,i) =>{
              return (
                <div className='linkContainer' key={i}>
                  <a href={m.url}>{m.title}</a>
                </div>
              )
            })
          }
        </HStack>

      </StyledNavBar>

    </>
  )
}

export default Home
